// angular-frontend/src/app/task-list/task-list.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-task-list',
    standalone: true,
    imports: [CommonModule],
    template: `
    <div>
      <h2>Code History
        <button class="btn-outline" style="margin-left: 10px" (click)="clearAll()">Clear All</button>
      </h2>
      <p *ngIf="tasks.length === 0">No submissions yet.</p>
      <ul style="list-style: none; padding: 0">
        <li *ngFor="let task of tasks" style="margin-bottom: 8px; border-bottom: 1px solid #ddd; padding-bottom: 8px">
          <strong>{{ task.name }}</strong> ({{ task.language || 'javascript' }})
          &mdash;
          <button class="btn-outline" (click)="runVerification(task._id)">Run &amp; Verify</button>
          <div *ngIf="results[task._id]"
               [class]="'result-box ' + (results[task._id].status === 'completed' ? 'pass' : results[task._id].status === 'failed' ? 'fail' : '')">
            <span *ngIf="results[task._id].status === 'running'">Running...</span>
            <span *ngIf="results[task._id].status === 'completed'">
              Passed<br><br>{{ results[task._id].output || '(no output)' }}
            </span>
            <span *ngIf="results[task._id].status === 'failed'">
              Failed<br><br>{{ results[task._id].error || results[task._id].output || 'unknown error' }}
            </span>
          </div>
        </li>
      </ul>
    </div>
  `,
    styles: []
})
export class TaskListComponent implements OnInit {
    tasks: any[] = [];
    results: any = {};
    private apiUrl = 'https://code-verification-backend.onrender.com/api';

    constructor(private http: HttpClient) { }

    ngOnInit() { this.getTasks(); }

    getTasks() {
        this.http.get<any>(this.apiUrl + '/tasks').subscribe({
            next: (data) => { this.tasks = data.data || data; },
            error: (err) => { console.log('Error', err); }
        });
    }

    runVerification(taskId: string) {
        this.results[taskId] = { status: 'running' };
        this.http.post<any>(this.apiUrl + '/executions/trigger/' + taskId, {}).subscribe({
            next: (data) => { this.pollResult(taskId, data.data._id, 0); },
            error: (err) => {
                console.log('Run failed', err);
                this.results[taskId] = { status: 'failed', output: 'Could not connect to server' };
            }
        });
    }

    private pollResult(taskId: string, execId: string, attempts: number) {
        this.http.get<any>(this.apiUrl + '/executions/' + execId).subscribe({
            next: (data) => {
                let exec = data.data;
                if (exec.status === 'completed' || exec.status === 'failed') {
                    this.results[taskId] = exec;
                } else if (attempts < 10) {
                    setTimeout(() => this.pollResult(taskId, execId, attempts + 1), 1000);
                } else {
                    this.results[taskId] = { status: 'failed', error: 'Timed out waiting for execution result. Please try again.' };
                }
            },
            error: (err) => { console.log(err); }
        });
    }

    clearAll() {
        this.http.delete(this.apiUrl + '/tasks').subscribe({
            next: () => { this.tasks = []; this.results = {}; },
            error: (err) => { console.log('Error clearing', err); }
        });
    }
}

// frontend/src/components/TaskList.jsx
import { useEffect, useState } from "react"

export default function TaskList() {
    const [arr, setArr] = useState([])
    const [results, setResults] = useState({})

    async function getFromServer() {
        try {
            let resp = await fetch("https://code-verification-backend.onrender.com/api/tasks")
            if (!resp.ok) throw new Error("Server not reachable")
            let data = await resp.json()
            setArr(data.data || data)
        } catch (error) { console.log("Error", error) }
    }

    async function runVerification(taskId) {
        setResults(prev => ({ ...prev, [taskId]: { status: "running" } }))
        try {
            let resp = await fetch(`https://code-verification-backend.onrender.com/api/executions/trigger/${taskId}`, { method: "POST" })
            let data = await resp.json()
            let execId = data.data._id
            let attempts = 0
            const poll = async () => {
                try {
                    let r = await fetch(`https://code-verification-backend.onrender.com/api/executions/${execId}`)
                    let execData = await r.json()
                    let exec = execData.data
                    if (exec.status === "completed" || exec.status === "failed") {
                        setResults(prev => ({ ...prev, [taskId]: exec }))
                    } else if (attempts < 10) { attempts++; setTimeout(poll, 1000) }
                    else {
                        setResults(prev => ({ ...prev, [taskId]: { status: "failed", error: "Timed out waiting for execution result. Please try again." } }))
                    }
                } catch (e) { console.log(e) }
            }
            poll()
        } catch (error) {
            console.log("Run failed", error)
            setResults(prev => ({ ...prev, [taskId]: { status: "failed", output: "Could not connect to server" } }))
        }
    }

    async function clearAll() {
        try {
            await fetch("https://code-verification-backend.onrender.com/api/tasks", { method: "DELETE" })
            setArr([])
            setResults({})
        } catch (error) { console.log("Error clearing", error) }
    }

    useEffect(() => { getFromServer() }, [])

    return (
        <div>
            <h2>Code History <button className="btn-outline" style={{ marginLeft: "10px" }} onClick={clearAll}>Clear All</button></h2>
            {arr.length === 0
                ? <p>No submissions yet.</p>
                : <ul style={{ listStyle: "none", padding: 0 }}>
                    {arr.map((a, index) => (
                        <li key={index} style={{ marginBottom: "8px", borderBottom: "1px solid #ddd", paddingBottom: "8px" }}>
                            <strong>{a.name}</strong> ({a.language || "javascript"})
                            {" — "}
                            <button className="btn-outline" onClick={() => runVerification(a._id)}>Run &amp; Verify</button>
                            {results[a._id] && (
                                <div className={`result-box ${results[a._id].status === "completed" ? "pass" : results[a._id].status === "failed" ? "fail" : ""}`}>
                                    {results[a._id].status === "running"
                                        ? "Running..."
                                        : results[a._id].status === "completed"
                                            ? `Passed\n\n${results[a._id].output || "(no output)"}`
                                            : `Failed\n\n${results[a._id].error || results[a._id].output || "unknown error"}`
                                    }
                                </div>
                            )}
                        </li>
                    ))}
                </ul>
            }
        </div>
    )
}
