// angular-frontend/src/app/app.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <div class="app-container">
      <div class="header">
        <h1>Code Verification System</h1>
        <p>Submit code and verify if it runs correctly</p>
      </div>

      <div class="nav-links">
        <a href="https://code-verification-system.vercel.app"><button class="btn-submit">Submit</button></a>
        <button class="btn-run" routerLink="/list" routerLinkActive="active-link">Run</button>
        <button class="btn-stats" routerLink="/stats" routerLinkActive="active-link">Stats</button>
      </div>

      <router-outlet />
    </div>
  `,
  styles: []
})
export class App { }

// frontend/src/App.jsx
import TaskForm from './components/TaskForm.jsx'
import './index.css'

export default function App() {
    return (
        <div className="app-container">
            <div className="header">
                <h1>Code Verification System</h1>
                <p>Submit code and verify if it runs correctly</p>
            </div>
            <div className="nav-links">
                <button className="btn-submit">Submit</button>
                <a href="https://code-verification-system-angular.vercel.app/list"><button className="btn-run">Run</button></a>
                <a href="https://code-verification-system-angular.vercel.app/stats"><button className="btn-stats">Stats</button></a>
            </div>
            <TaskForm />
        </div>
    )
}
